# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
# Reference: https://github.com/PowerShell/PowerShell/blob/master/docs/building/windows-core.md
properties:
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: Install .NET SDK preview
        allowPrerelease: true
      settings:
        id: Microsoft.DotNet.SDK.Preview
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      directives:
        description: 'Install Microsoft Visual Studio Code'
        allowPrerelease: true
      settings:
        id: Microsoft.VisualStudioCode
        source: winget
  configurationVersion: 0.2.0